name: ${project.name}
version: ${project.version}
description: '${project.description}'
author: Programie
website: ${project.url}
main: com.selfcoders.retainxp.RetainXP
permissions:
  retainxp.retain:
    description: 'Retain XP on death'
    default: true